travis:
  secure:
    BINSTAR_TOKEN: HwqMXW92JyCwsLIMITTnm8QPecP3uyupK/KzmRqIccOdPijYCjpZCImMIlD6mn1/BdjxQ+BAeQIvdbVS/yDFtlsQsNldmYh8RESsL3BeLbAC6xidlh8P45jx7PKPBFPlqZ2m/5Yji0OBY1VhRGZN+ueVwocWAFGlfsTsstqiREmbn5mHQqwg1A9lOrB4rtsSwJVMyxSumktODrD593Otne9HQce61SOv7l7ljMe7e5//YyP2xJhJn7bnlilWIoujVOtxLnr6wewEANeRuV/YHWgmhrpK8dZmh1d0aSsXgljZictoetZrBQJO9VVY4qiBcArz6vZdD1kW1JR5l3rS0f2cAAHyC5tx22cepE+MM/FG6jypzYKFWwCQHCwye0duHdnSr4B9PHy/4JS16Rx0hbgBwd32tdjB51alzqQlpSuAIySSHASiIyOzz4gFM0cYIU/L9Q3eX+cqJqjxh8RyKbo2ur8YKL0TOxa5TKLmoYjrO8pOV/hJOD2Nncp3th0BTB1Aqzzw5FeoKb9Ga2+rxzEaVdBiN57w/QgMwQ+R+njQFynLnXWBBh71FDZX7mbEM7/IlUwmoadrMMsdJS/n2j7DSWHAGrbV0v+EaIg6tJJKIbn0OZNd62Jye2L3T7nQsOIa0lb7Ll5wQ5QQkaU2OrRsEAizK/YHJwvUK6r8cVo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
